def get_workflow_url():
    """
    Get Workflow URL responsible for the Action run.
    """
    repo = os.getenv('GITHUB_REPOSITORY')
    github_token = os.getenv('GITHUB_SECRET')
    url = f'https://api.github.com/repos/{repo}/actions/workflows'
    headers = {
        'Accept': 'application/vnd.github.v3+json',
        'Authorization': f'token {github_token}',
    }
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        return
    workflows = response.json()['workflows']
    for workflow in workflows:
        if workflow['name'] == os.getenv('GITHUB_WORKFLOW'):
            return workflow['html_url']
