name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag web-pair-qr:latest
    - name: Display workflow URL
      run: echo "Workflow run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    - name: Send notification
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            "text": "Workflow completed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "attachments": [{
              "color": "${{ job.status == 'success' && 'good' || job.status == 'failure' && 'danger' || 'warning' }}",
              "text": "Build ${{ job.status }}"
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
